version: "3"
#use same version for E, L and K for compatibility

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: my_elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - my_elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: my_kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    networks:
      - my_elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.3
    container_name: my_logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - my_elk_network
    depends_on:
      - elasticsearch

#list the networks of ELK
networks:
  my_elk_network:  #custom network name
    driver: bridge

#list the volumes that you mount into the container volume
volumes:
  elasticsearch_data:
    driver: local
